import datetime

today = datetime.datetime.today()

testcases = {
    "2017.08.03 03:04:05": datetime.datetime(year=2017, month=8, day=3, hour=3, minute=4, second=5),
    "05.05.2017 03:04:10": datetime.datetime(year=2017, month=5, day=5, hour=3, minute=4, second=10),
    "10.01.2022": datetime.datetime(year=2022, month=1, day=10),
    "2023.01.10": datetime.datetime(year=2023, month=1, day=10),
    "03:02:10": datetime.datetime(year=today.year, month=today.month, day=today.day, hour=3, minute=2, second=10),
    "01.01.2023 05:03": datetime.datetime(year=2023, month=1, day=1, hour=5, minute=3),
    "07:16": datetime.datetime(year=today.year, month=today.month, day=today.day, hour=7, minute=16),
    "08:20": datetime.datetime(year=today.year, month=today.month, day=today.day, hour=8, minute=20),
    "second day after christmas": datetime.datetime(year=today.year, month=12, day=27),
    "3rd week of august": datetime.datetime(year=2022, month=8, day=22),
    "4. week of august": datetime.datetime(year=2022, month=8, day=29),
    "1st of august": datetime.datetime(year=2022, month=8, day=1),
    "fifth month of 2021": datetime.datetime(year=2021, month=5, day=1),
    "second day after august": datetime.datetime(year=2022, month=8, day=2),
    "3 months before the fifth week of august": None,
    "10 days and 2 hours after 3 months before christmas 2020": None,
    "a day and 3 minutes after 4 months before christmas 2021": None,
    "3 minutes and 4 hours, 2 seconds after new years eve 2000": None,
    "next 3 years and 2 months": datetime.datetime(today.year + 3, today.month + 2, today.day, today.hour, today.minute, today.second),
    "in 2d, 500 h 2 seconds and 4 minutes": None,
    "2 days after christmas 2023": None,
    "infinity": -1,
    "inf": -1,
    "in 1Y 2m 3W 3d 5H 6M 7S": None,
    "in 1 Year 2 months 3 weeks 4 days 5 hours 6 minutes 7 seconds": None,
    "in a year and in 2 months, in 3 seconds and 4 days": datetime.datetime(today.year + 1, today.month + 2, today.day + 4, today.hour, today.minute, today.second + 3),
    "for a year": datetime.datetime(today.year + 1, today.month, today.day, today.hour, today.minute, today.second),
    "for 2 days and 1 year": datetime.datetime(today.year + 1, today.month, today.day + 2, today.hour, today.minute, today.second),
    "1 year 10 seconds": datetime.datetime(today.year + 1, today.month, today.day, today.hour, today.minute, today.second + 10),
    "two years 3 minutes and 1 hour": datetime.datetime(today.year + 2, today.month, today.day, today.hour + 1, today.minute + 3, today.second),
    "next 2 years": datetime.datetime(today.year + 2, today.month, today.day, today.hour, today.minute, today.second),
    "last 4 years": datetime.datetime(today.year - 4, today.month, today.day, today.hour, today.minute, today.second),
    "next three months": datetime.datetime(today.year, today.month + 3, today.day, today.hour, today.minute, today.second),
    "next christmas": datetime.datetime(today.year, 12, 25),
    "christmas": datetime.datetime(today.year, 12, 25),
    "new years eve": datetime.datetime(today.year, 12, 31),
    "xmas 2025": datetime.datetime(2025, 12, 25),
    "next friday": None,
    "next second": datetime.datetime(today.year, today.month, today.day, today.hour, today.minute, today.second + 1),
    "last month": datetime.datetime(today.year, today.month - 1, today.day, today.hour, today.minute, today.second),
    "next hour": datetime.datetime(today.year, today.month, today.day, today.hour + 1, today.minute, today.second),
    "next year": datetime.datetime(today.year + 1, today.month, today.day, today.hour, today.minute, today.second),
    "eastern 2010": datetime.datetime(2010, 4, 4),
    "halloween 2030": datetime.datetime(2030, 10, 31),
    "next april fools day": datetime.datetime(today.year, 4, 1),
    "thanksgiving": None,
    "next st patricks day": None,
    "valentine day 2010": datetime.datetime(2010, 2, 14),
    "summer": datetime.datetime(today.year, 6, 1),
    "winter 2021": datetime.datetime(2021, 12, 1),
    "next spring": datetime.datetime(today.year, 3, 1),
    "begin of fall 2010": datetime.datetime(2010, 9, 1),
    "summer end": datetime.datetime(today.year, 8, 31, 23, 59, 59),
    "end of winter": datetime.datetime(today.year, 2, 28, 23, 59, 59),
    "end of the spring": datetime.datetime(today.year, 5, 31, 23, 59, 59),
    "end of autumn 2020": datetime.datetime(2020, 11, 30, 23, 59, 59),
    "begin of advent of code 2022": datetime.datetime(2022, 12, 1, 6),
    "end of aoc 2022": datetime.datetime(2022, 12, 26, 6),
    "end of the year": datetime.datetime(today.year, 12, 31, 23, 59, 59)
}
